spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: qwerty
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  token:
    security: soymun
    validate: 3600000


